name: Homebrew

on:
  release:
    types: [published]

jobs:
  homebrew-releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: schneik80
          homebrew_tap: homebrew-fusiondatacli
          formula_folder: Formula
          github_token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          commit_owner: homebrew-releaser
          commit_email: homebrew-releaser@example.com
          install: 'bin.install "fusiondatacli"'
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
          target_linux_arm64: true
          debug: false
